baseURL = "https://kobnar.github.io/"
languageCode = "en-us"
title = "Konrad R.K. Ludwig"

[[module.imports]]
    path = "github.com/rhazdon/hugo-theme-hello-friend-ng"

[params]
    dateform = "Jan 2, 2006"
    dateformShort = "Jan 2"
    dateformNum = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04"
    math = true

    # Home page
    homeSubtitle = "Data Anlyist // Software Engineer"

    disableReadOtherPosts = false
    enableSharingButtons = false

    # Metadata for document head
    description = ""
    keywords = ""
    images = [""]

    [params.portrait]
        path = '/images/kobnar_avatar.jpg'
        alt = ''
        maxWidth = '20rem'

    [[params.social]]
        name = 'github'
        url = 'https://github.com/kobnar/'
    
    [[params.social]]
        name = 'linkedin'
        url = 'https://linkedin.com/in/konradrkludwig/'
    
    [[params.social]]
        name = 'twitter'
        url = 'https://twitter.com/kobnar/'

[taxonomies]
    category = "categories"
    tag      = "tags"
    series   = "series"

[languages]
    [languages.en]
        title = "Konrad R.K. Ludwig"
        subtitle = "Data Anlyist // Software Engineer"
        keywords = ""
        copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
        readOtherPosts = "Read other posts"

    [languages.en.params.logo]
        logoText = "kobnar"
        logoHomeLink = "/"

# And you can even create generic menu
[[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 1
[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    identifier = "references"
    name = "References"
    url = "/references/"
    weight = 3