baseURL = "https://kobnar.github.io/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Konrad R.K. Ludwig"

[[module.imports]]
    path = "github.com/Fastbyte01/KeepIt"

paginate = 12
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[Permalinks]
 posts = "/:year/:month/:filename/"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "References"
    url = "/references/"
    weight = 3

  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 4

[params]
    since = 2022
    author = "Konrad R.K. Ludwig"
    subtitle = ""
    cdn_url = ""
    home_mode = ""
    dateFormatToUse = ""
    avatar = "/images/kobnar_avatar.jpg"
    description = ""
    keywords = ""
    license = 'Released under <a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
    copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."

    [author]
    name = "Fastbyte01"

    [params.publisher]
        name = "Fastbyte01"

        [params.publisher.logo]
        url = "logo.png"
        width = 127
        height = 40

#    [params.logo]
#        url = "logo.png"
#        width = 127
#        height = 40

#    [params.image]
#        url = "cover.png"
#        width = 800
#        height = 600

    [params.social]
        GitHub = "kobnar"
        Twitter = "kobnar"
        Linkedin = "konradrkludwig"
        #Instagram = "xxxx"
        #Email   = "xxxx"
        #Medium = "xxxx"
        #Gitlab = "xxxx"
        #Youtubelegacy = "xxxx"
        #Youtubecustom = "xxxx"
        #Youtubechannel = "xxxx"
        #Keybase = "xxxx"
        #Codepen = "xxxx"
        #Bitbucket = "xxxx"
        #Stackoverflow = "xxxxx"
        #Paypal = "xxxx"
        #Patreon = "xxxx"
        #Angellist = "xxxx"
        #Googlescholar = "xxxx"
        #Researchgate = "xxxx"

    [params.share]
        Twitter = true
        Linkedin = true

#    [params.gitalk]
#        owner = ""       # Your GitHub ID
#        repo = ""        # The repo to store comments
#        clientId = ""    # Your client ID
#        clientSecret = "" # Your client secret

#    [params.utterances]       # https://utteranc.es/
#        owner = ""              # Your GitHub ID
#        repo = ""               # The repo to store comments

#    [params.gitment]          # Gitment is a comment system based on GitHub issues. see https://github.com/imsun/gitment
#        owner = ""              # Your GitHub ID
#        repo = ""               # The repo to store comments
#        clientId = ""           # Your client ID
#        clientSecret = ""       # Your client secret