baseURL = 'https://kobnar.github.io/'
languageCode = 'en-us'
title = 'Konrad R.K. Ludwig'
paginate = 10

[[module.imports]]
    path = 'github.com/Mitrichius/hugo-theme-anubis'

[params]
    author = 'Konrad R.K. Ludwig'
    email = 'konrad.rk.ludwig@gmail.com'
    avatar = '/images/kobnar_avatar.jpg'
    description = 'A personal site.'
    style = 'dark-without-switcher'
    paginationSinglePost = true
    readMore = false
    readNextPosts = 0
    disableSummary = false
    copyCodebutton = true
    rssAsSocialIcon = true

    [[params.social]]
        id = 'github'
        name = 'kobnar'

    [[params.social]]
        id = 'linkedin'
        name = 'konradrkludwig'

[[menu.main]]
    identifier = 'About'
    name = 'About'
    title = 'About'
    url = '/about/'
    weight = 2

[[menu.main]]
    identifier = 'References'
    name = 'References'
    title = 'References'
    url = '/references/'
    weight = 1

[[menu.main]]
    identifier = 'Posts'
    name = 'Posts'
    title = 'Posts'
    url = '/posts/'
    weight = 0
