baseURL = 'https://kobnar.github.io/'
languageCode = 'en-us'
title = 'Konrad R.K. Ludwig'

[[module.imports]]
    path = 'github.com/luizdepra/hugo-coder'
    
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# See: https://github.com/luizdepra/hugo-coder/wiki/Configurations#theme-parameters
[params]
    author = "Konrad R.K. Ludwig"
    info = "Data Analyst / Software Engineer"
    avatarurl = "images/kobnar_avatar.jpg"
    math = true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"
    author = "authors"

# Social links
[[params.social]]
    name = "Github"
    icon = "fa fa-github fa-2x"
    weight = 1
    url = "https://github.com/kobnar/"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin fa-2x"
    weight = 2
    url = "https://linkedin.com/in/konradrkludwig/"

# Menu links
[[menu.main]]
    name = "Posts"
    weight = 1
    url  = "posts/"
[[menu.main]]
    name = "References"
    weight = 2
    url = "references/"
[[menu.main]]
    name = "About"
    weight = 3
    url = "about/"